FROM apache/airflow:2.9.1-python3.11
USER airflow
RUN pip install --no-cache-dir dbt-postgres==1.8.0 gtfs-realtime-bindings==1.0.0 protobuf==4.25.3 requests==2.31.0 psycopg2-binary==2.9.9 python-dotenv==1.0.1 tenacity==8.2.3
